language: php

env:
  global:
    - GLPI=master
    - DB=mysql

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: 7.0
      addons:
        mariadb: 10.2
    - php: 7.1
      env: CS=true
      addons:
        mariadb: 10.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
 - cd ..
 - git clone --depth=10 -b $GLPI git://github.com/glpi-project/glpi.git glpi
 - cd glpi
 - composer install --no-dev -o
 - mysql -u root -e 'create database glpi;'
 - php scripts/cliinstall.php --db=glpi --user=root --tests
 - cp config/config_db.php ../fusioninventory-for-glpi/tests/
 - cd ..
 - mv -f fusioninventory-for-glpi glpi/plugins/fusioninventory

before_script:
  - phpenv version-name | grep ^5.[34] && echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - phpenv version-name | grep ^5.[34] && echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - php -S localhost:8088 -t glpi > /dev/null 2>&1 &
  - cd glpi/plugins/fusioninventory
  - composer install --optimize-autoloader

script:
 - mysql -u root -e 'select version();'
 - vendor/bin/atoum --debug --force-terminal --configurations tests/telemetry.php --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/units

after_script:
 - cp -fr build glpi/plugins/fusioninventory/
 - cd glpi/plugins/fusioninventory/
 - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/robo --no-interaction code:cs; fi

